#!/bin/bash
###exit status###
#Severity status down	        1	critical
#Severity status unknown	2	critical
#Severity status starting 	3	warning
#Severity state halted		4	warning
#Severity state failed		5	critical
#Severity state unknown		6	critical
#Severity state reforming	7	warning
#Severity auto_run disabled	8	warning
###Vars###
cmd=/usr/local/cmcluster/bin/cmviewcl
log=/var/log/cluster_status
###
###Chech if cluster was halted from os side.
if (tail -100 /var/log/messages |grep 'Stopping LVM2');then
    date >> $log
    grep -C2 'Stopping LVM2' /var/log/messages >> $log
	echo "Node halted not gracefully" >> $log
	exit 9
fi
#Extended cluster status check
if [ -f /nsr/ptausioffline_CV ]; then
   date >> /var/log/cluster_status
   echo "Backup job is running" > /var/log/cluster_status
   exit 0
elif  (tail -100 /var/log/messages |grep 'maintenance');then
   date >> /var/log/cluster_status
   grep -C2 'maintenance' /var/log/messages >> $log
   echo "Cluster package is in maintenance." >> /var/log/cluster_status
   exit 0
else
	if $cmd |awk '{print $2}'|grep 'down'; then
	date >> $log
	echo 'Severity status down' >> $log
	$cmd -f table -l package|grep 'down'  >> $log
	exit 1 
	
	elif $cmd |awk '{print $2}'|grep 'unknown'; then
	date >> $log
	echo 'Severity status unknown' >> $log
	$cmd -f table -l package|grep 'unknown'  >> $log
	exit 2 
	
	elif  $cmd |awk '{print $2}'|grep 'starting';then
	date >> $log
	echo 'Severity status starting '
	$cmd -f table -l package|grep 'starting'  >> $log
	exit 3 
	
	elif  $cmd |awk '{print $3}'|grep 'halted';then
	date >> $log 
	echo 'Severity state halted' >> $log
	$cmd -f table -l package|grep 'halted'  >> $log
	exit 4 
	
	elif  $cmd |awk '{print $3}'|grep 'failed';then
	date >> $log
	echo 'Severity state failed' >> $log
	$cmd -f table -l package|grep 'failed'  >> $log
	exit 5 
	
	elif  $cmd |awk '{print $3}'|grep 'unknown';then  
	date >> $log
	echo 'Severity state unknown'   >> $log
	$cmd -f table -l package|grep 'unknown'  >> $log
	exit 6  
	
	elif  $cmd |awk '{print $3}'|grep 'reforming';then
	date >> $log
	echo 'Severity state reforming' >> $log
	$cmd -f table -l package|grep 'reforming'  >> $log
	exit 7 
	
	elif  $cmd |awk '{print $4}'|grep 'disabled';then
	date >> $log
	echo 'Severity auto_run disabled' >> $log
	$cmd -f table -l package|grep 'disabled'  >> $log
	exit 8 
	
	else
	date >> $log
	echo 'Cluster is in good state' >> $log
	exit 0
	
	
	fi
fi	
